<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <h1>Article 1</h1>
        <p>
        Journal of Information & Optimization Sciences
ISSN 0252-2667 (Print), ISSN 2169-0103 (Online)
Vol. 44 (2023), No. 3, pp. 475-492
DOI : 10.47974/JIOS-1407
Co-CEP: A co-designed community engagement protocol as a catalyst for cybersecurity research in Africa: The case of northern Namibia
Gabriel Tuhafeni Nhinda *
Fungai Bhunu Shava †
Namibia University of Science and Technology
Faculty of Computing and Informatics
13 Jackson Kaujeua Street
Windhoek Namibia

Abstract
     Through technology, the world has become a global village, connecting geographically distant people into virtual neighbors. This presents many opportunities for individuals, businesses, and remote communities. The advantages of this connectivity have been brought to the fore by COVID-19, as technology and the Internet kept the world connected and functioning. However, in Africa, although much has been done on connecting the unconnected, there remains rural underserved communities. Notwithstanding the benefits of technology and the Internet, the cyber-safety and cybersecurity of those communities living on the fringes of society - rural underserved communities - is unknown. Consequently, many researchers, noting the benefits of technology, have embarked on ICT for Development projects (ICT4D). However, community based ICT4D projects have been failing due to myriad of factors. Some such factors are engagement misalignment, cultural faux pas', communication, power dynamics and community-buy-in of end-products. With the propensity to circumvent the shortcomings indicated above, Participatory Design (PD) processes may be utilized. Codesign extends PD by allowing researchers and participants to be equals in the creation of solutions to problems contrary to traditional research approaches, that abstract researchers from the community within which they work. As an effort to address these challenges, we present a co-designed community engagement protocol (co-CEP) for rural underserved communities in Northern (Oukwanyama), Namibia. This study was qualitative, guided by Ubuntu and Uushiindaism tenets of trust, neighbourliness, respect, familiarity, hospitality, and collective unity as pillars of fostering communication within 4 villages in Oukwanyama, 

This research was conducted during the COVID-19 Pandemic and it was sponsored by a grant from the Mobile Telecommunications Company (MTC) Namibia.
* E-mail: gnhinda@nust.na (Corresponding Author)
† E-mail: fbshava@nust.na
(c)
Namibia. The aim was to understand the concepts of how information flows in order to get engagement from community members for cybersecurity research. We held 4 co-design sessions in 4 villages, with each feeding into the next. The presented co-CEP comprises of 13 elements that are key to successful community engagement within community-based technology projects, especially cybersecurity research. The co-CEP is part of a research study on co-designing cybersecurity practices with rural underserved communities.

Subject Classification: Primary 93A30, Secondary 49K15.
Keywords: Cybersecurity, Co-design, Community engagement, Africa, Ubuntu, Uushiindaism. 
1. Introduction
    Through technology, the world has become a global village, connecting geographically distant people into virtual neighbors. Globally, there has been a great increase of new Internet users joining as catalyzed by COVID-19. According to International Telecommunication Union (ITU) [1] there has been a 17% estimated growth in Internet users in 2021, resulting in a 63% global population of Internet users. Compared to 53% in 2019 pre-COVID-19. These new connections to the Internet can be attributed to the higher investment in Internet infrastructure by governments and Internet service providers alike. The ITU further reports that there have been significant strides made in Internet infrastructure investments, bringing close to 95% of the world population within mobile broadband range. Internet connectivity has given way for the connection of previously marginalized communities in remote and rural areas. However, there remains pockets of underserved communities. The ITU reports that more than an estimated 30% of the African continent does not have access to mobile broadband services albeit the infrastructural investments. With greater investment from telecommunications operators to reach these edge communities, not much is being done in the realm of understanding their digital luminaries.
    Even though the access-to-Internet gap is fast closing, a new divide is emerging, the cybersecurity divide. According to [2] there exists computing devices with Internet connectivity capabilities in rural villages. With each household in their South African case study reported to own at least one mobile phone and accessing Internet through that one device. Although the ownership and access to Internet enabled computing devices was characterized as either using someone else mobile device [3], inserting their Subscriber Identity Module (SIM) card into another's mobile device or 'topping up' pre-paid mobile 'skolo' to enable broadband Internet access [4].The presence of mobile devices as the prominent computing devices is congruent with [5] who reported a 41.3% mobile phone ownership rate in rural areas. [6] further indicated that, although mobile devices including smartphones exist in rural communities, they are underserved with broadband and electricity access, notwithstanding the cost of Internet access in rural villages. In Namibia the preferred mode of Internet access is mobile devices, due to their ubiquitous nature [7], [8].
    The popularity of mobile computing devices in rural communities' leaves room for security risks and attacks by unaware and inexperienced end users. Even though according to [9] mobile computing devices are equipped with various security options. Rural communities may or may not be aware of these modes of securing themselves, and there is a dearth of literature in the modes in which rural communities utilize those security options [10]. However, prior to any security studies being conducted to understand these gaps, there is a need to also understand how best to engage local indigenous rural communities. As such, this study sought to co-design a community engagement protocol from our ongoing longterm case study in northern Namibia. This is imperative to success of cybersecurity research as local values and protocols can promote or deter participation in any activities happening within a community, including embodiment of knowledge [11], [12]. The importance of community engagement frameworks and in-turn protocols was also noted by, [13] who proposed any future work to endeavour to co-design community engagement frameworks as any negotiations that occur with research members not familiar with local customs can breed mistrust.
    This paper is organized as follows. In section 2 the related work is discussed, followed by the methodology applied in this study in section 3. We proceed with section 4, presenting the co-design community engagement protocol. Section 5 gives a discussion of the findings, presentation of the limitations and conclusions.
2. Related Work
    Research within rural communities is not a new and has been in existence for a while in various fields of study, ranging from health [14], [15] and political science [16] of research. Within the cybersecurity area, research in rural areas is receiving considerable attention in other parts of the world [17], [18]. However, in African there is limited literature in this space. 
    Literature that speaks to research in rural African context, barely indicates how they engaged the communities other than alluding to a set of guiding principles or adherence to "existing community structures and protocols" [19]. Therefore, as [19] put it the "creation of relationships and building and maintaining of trust" is a major concern in participatory based research project in rural African communities. Especially if the researchers come from a different ontological, cultural and language background to those of the rural communities. 
    Cybersecurity is often defined from the organisational or national perspective [20-21], looking at the protection of information assets through technological means [22]. It is also an accepted fact that many cybersecurity breaches are facilitated by the weakness of human or through human error [10], [23]. [10] argue that the human factor needs to be brought to the fore. Specifically looking at rural African communities, to understand how those communities protect themselves and how they conceptualize risk.
    Within cybersecurity research, community engagement is often dictated by "expert researchers" [24] in collaboration with a few leaders within a particular community. The assumption is that leaders have the best interest of the community at heart. However, [25] argued that from their case study in the informal settlements of cape town, there was need to be cautious of bottlenecking by those leaders and thereby also ensuring relevant and not 'convenient' participants are engaged in communitybased work. 
    [26] interrogated the level of community engagement in research projects. They noted that even though workshops and guides exist for researcher entering a new community, they are not always enough, hence, continual training is necessary. Additionally, there is a need to work towards transforming community engagement from informants to partners. This challenge can be perceived from the contextualization of the understanding of technology by rural community inhabitants. For instance, [8]'s study found that for rural areas with broadband access, the "access to Internet gap" was closing and this access is facilitated through mobile devices [24]. They further found that most adolescents including those in rural areas are at cyber risk of sexting, exposure to violent videos, harmful user-generated content, and cyberbullying among other risks. However, these cyber risks may not be perceived as cyber risks by users in rural areas [27] since the enabling technological devices are seen as positive tools bringing "development". Thus, making it difficult to be equal collaborators within co-design-based research projects with rural communities. Similarly, [28] also argue that the level of involvement needs to be clearly articulated and there needs to be a fundamental honesty about participants level of "participation". Often, within academic research this can be challenging due the academic process, for instance contact is only made after ethical clearance has been achieved. This means that participants do not have a philosophical impact on the research direction or the framing of the project.
2.1 Implications of co-design for community engagement protocols
    According to [29] researchers engaged in designing technological artefacts for communities whose social environment is discreet from their own tend to rely upon existing methodologies like design science research. She postulates that these methodologies do not provide how to engage with local communities outside of software engineering elicitation which leads to project failure due to a "mismatch between IS designs and local user actuality". She adds that this can sometimes be a result of preconceived notions about the contextual reality of communities. [30] argue that participation in local rural African communities is an established practice, however, the focus of participatory based methods' framing of participation differs. 
    Thus, the focus of participation challenges the role of a researcher under the ubuntu principle as researchers being part of the community. They postulate that design researchers need to accept negotiated power dynamics thereby violating their pre-defined roles in design projects. This level of morphosis by design researchers also includes co-determining participation meaning with rural communities [19] taking away reliance on existing PD methods framing of participation. Therefore, co-designing a community engagement protocol could be useful to design researchers to build the trust at initial stages of project design, communities may not be partners or project designers, but they can be research partners [28].
3. Methodology
    This research is exploratory in nature, and a qualitative approach under multiple case studies, viewing each case site as an independent case study. Co-design sessions were used as the data collection instrument. Participant recruitment and selection was guided by existing practices in the rural community's context. Often this means all residents are invited by village headman, Kapatashu and by neighbors to a community meeting wherein the co-design sessions took place.
    The co-design sessions were audio recorded with pictures taken at random intervals. The data was transcribed from audio recordings and translated from Oshikwanyama (Oshiwambo) to English. Co-design was chosen as it increases the chances of artefact buy-in, success and acceptability of a project [26] from the design process. This research aimed to co-design a community engagement protocol following a twostep approach. Firstly, to understand how to make first contact, using the proposed research approach by [10]. [10]propose that the first step in the process is to identify inroads into the community with whom you wish to research through desktop research about the community, identification of a community liaison, then conducting the co-design sessions with the community once all relevant permissions have been acquired. Secondly, with the aim of co-designing a community engagement protocol for getting the relevant trust and cybersecurity information to community members. It is worth noting that, even though [10] provide a proposed approach for co-design-based engagement, they do not indicate the level of co-design that rural community participants would have in proposed interactions.
• We first sourced ethical clearance from the university's ethical  clearance committee to apply Ubuntu and Uushiindaism tenets as part of the data collection guidance. 
• Secondly, we sought permissions from the local Constituency  Councilor to allow us to conduct research in his jurisdiction, as well as from the senior village headman that is responsible for the villages, we intended to conduct our study. The senior village headman served as an intermediary to the junior headmen that oversee smaller villages. He delegated the responsibility of recruiting participants for the co-design sessions based on the information shared by the researcher to the junior headman. 
• Thirdly, consensus was reached between the two, the junior headman  communicated to their 'Kapatashu(s)', someone who is responsible for sections of a village to manage administrative tasks. 
• Fourth, the Kapatashu sought the consent of the villagers through  Short Message Service (SMS) and word-of-mouth when neighbors met each other while rendezvousing and finding the respective meeting location (all co-design sessions were held under the shade of trees (Jackals berry and wild fig trees). 
• In step 5 we conducted the co-design sessions following a  community meeting style where the discussions were led for equal participation. The co-design sessions were conducted at the respective village headman's homestead or a representative of theirs (as in the case of Case Site 2 - headman's representative - and 3 -Kapatashu arranged a tree in the village -). The headman's assistant at Case site 4 was a retired teacher volunteered to help the elderly headman with running the affairs of the village but was not in the capacity of Kapatashu. The co-design sessions at Case sites 1 and 4 were co-led with the assistance of an appointed participant from the village (see figure 1 and Figure 2). Being that the Oshiwambo preserve knowledge through 'primary orality' [31], some of the parts of speech were translated by an Oshiwambo expert, as they formed part of idioms not known to the researcher. An example of this was when CaseSite1OM1 was narrating his negative experience with a telephonic scammer, he referred to "Ondiba ei walya, Aame ndeyi dipaya" which if directly translated would read "The rabbit that you ate, I killed". However, after the expert translation, it read "I am aware that you are trying to scam/fool me and you might as well stop". This approach of incorporating idiomatic (proverbs) expressions in technology research is supported by [32] who posits that Africans have greater expression of needs, intended meaning and experiences when using their native languages in form. Thus, requirements for information systems (and cybersecurity) can be fully elicited as part of a socio-technical systems. 
• The six step was done after each co-design session the main  researcher with the assistance of a research assistant performed reflections that informed the direction of the next co-design sessions. The transcribed data was analysed through thematic content analysis, and this is congruent with the underlying theories applied to understand the community at hand of Ubuntu [33] and Uushiindaism [34]. Specifically, we were guided on the tenets of trust, neighbourliness, respect, familiarity, hospitality, and collective unity as pillars of fostering communication. After steps there was also a need to correspond with the junior headman of the village that was being visited next. This was to re-confirm and arrange for logistics on the meeting. Once, for CaseSite3 we had to re-schedule as the headman had forgotten to remind the villagers of the community meeting.
• In step 7, the design of the harmonized co-designed community  engagement protocol after 4 co-design sessions at all four case sites was conducted. The overarching structure of the engagement protocol models the traditional flow of information for the local community in harmony with national political structures of governance. As such we identified that, there exist a variety of governance structures within the traditional OvaKwanyama kingdom. First, from Case Site 1, we learned that there are junior headsmen, that report to a senior headman. The senior headman who was situated in Case site 2 then controls the villages under the headmanship of junior headman, who in turn brings matters of complexity to "ediko" (loosely translated to the fireplace) for adjudication to the senior headman. The senior headmen then report to "omalenga" who serve as advisors to the Queen of Oukwanyama and control of clusters of villages. Similarly, we can understand that each village may have more than one Kapatashu depending on the size of the village. The inclusion criteria were all residents of the respective village. It is however difficult to limit the number of attendees as within rural 

Figure 1
Followed research process
communities, meetings are rarely limited as prescribed in western research methods. The composition of attendees were mostly youths, comprised of university students, out of school youths, and some village elders.
    Figure 1 presents the process followed as described above, adding the acquisition of research ethical clearance as first part of our process.
3.1 Case sites
    In Namibia, tribes to an extent have similar ethos in our rural communities that governs our way of being, which to a greater extent is like other African rural communities. This is because we come from the same root. The case sites for this research are part of the Aawambo people, which is a cluster of various sub-tribes. The Aawambo in general have an abstract homogeneity in language, social interactions, and governance structures, with some variances that are context specific. The Aawambo have 12 mutually intelligible dialects (due to morphology, syntax, and semantics) of which only Oshikwanyama and Oshindonga have been accepted as standardized written languages [35, p. 111]. The overarching language is referred to as Oshiwambo. 
    The research was conducted in 4 villages within the Oukwanyama kingdom. The villages are comprised mostly of Oshikwanyama speakers with some residents being proficient in English in the form of professionals (teachers, nurses, police officers, immigration officials) and students. Even though the [36] reports that the constituency wherein this research took place enjoys an 90.4% literacy rate for the population aged 15 years and above, our experience was that more than half of our participants were barely conversant in English and preferred to converse in Oshikwanyama. The demarcations of villages are not always rural village homesteads; there are also remnants of development, in the form of electricity being available in Case Site 1 due to the school in the village. Case Site 2 for instance is split into the village portion and the town portion. The town portion enjoys 4G access. The other half is the village portion whose access to Global System for Mobile Communications (GSM) is spotty and broadband network access can be challenge unless as per our observations it is between 23:00-04:00 on the MTC network, we did not verify access with the other mobile operator. 
    The villages appear to have spotty GSM connection and limited access to broadband access. Thus, being underserved in terms of telecommunications, Case Site 1 for instance also has a road access problem, as when the annual floods occur, they are completely cut off from road networks and might have to rely to canoes as the Oshana's fill up with water for up-to 4 months each year. Due to their proximity to the AngolaNamibia border, many of the young people in the villages, especially Case Site 1 and 4 speak Portuguese as vernacular. The presented co-CEF went through 3 iterations, with each village informing and improving on previous designs. 
4. The Co-designed Community Engagement Protocol (co-CEP)
    The Co-CEP was optimized as per the designs from the co-design sessions. It has 12 key stakeholders that need to be informed and consulted. The end objective is getting the villagers to engage with researchers. Through the co-design sessions it became apparent that local constituency councilors and village headman sometimes do not communicate, it could also be an oversight. However, we came to understand that the councilor sometime tends to pronounce activities after they have provided permission without consulting the respective village headman for instance, this was a frustration indicated as "they think we work for them, however, they are working within our kingdom and not the other way" CaseSite3EM1.
    As indicated in Figure 2, the Co-CEP starts with the researcher presenting all relevant documentation including objectives and expected outcomes to the Local constituency councilor and the village headman. This activity can be completed in parallel as headman and councilors are not governed by the same laws. Councilors are elected by citizens through national laws while village headman are elected and ordained by the Queen of Oukwanyama and traditional laws and processes of the Oukwanyama kingdom are followed. There are interventions from the line ministry to appoint traditional leaders into adjudication positions to run local courts as part of the judicial system in the country. Governments way of avoiding crossing traditional leaders and leverage of synergies with the various kingdoms. Councilors do however from time to time inform village headman in their constituencies through radio of any activities that will be coming to their villages and further legitimizes researchers' pedigree to village headman. Sometimes this communication is done face-to-face or via telecommunications means, i.e., SMS, WhatsApp, or phone calls. Once the councilors give permission to researchers, they may without informing the village headman inform their constituents of the various activities that will be happening (research, cattle vaccinations, etc.) through the radio, indicating where the people are from, what they purpose is and the anticipated dates they will be in those areas (villages). They also inform the researchers via e-mail or telephonically.
    Co-design session participants also indicated that there is a need to have a local researcher that knows the language and area well. This person can also reach-back-home to parents or trusted members of the community known by the headman and/ councilor to assist with getting permissions. This according to participants was key as sometimes researchers tend to be young and might not be known to the village headman. In the instance that the researcher(s) travel to meet the village headman, there is a need for researchers to understand their family (at least 5 generations, including clan lineage) background, as these are used as part of the introduction phase, those introductions often take this form.
    "My name is XXX, my clan's name is, my father is XX, his father is XX, whose father is xx, etc, our matrilineal clan is XX our paternal clan is. My mother is XX, who is from XX village, her mother is xxx, her father is xxx, her clan is ... etc."

Figure 2 
Co-designed Community Engagement protocol (Co-CEP)
    This form of introduction allows the village headman and whomever else is present during the initial contact to gain familiarity with you and based on that, trust can be established, and permission granted. As per one of the tenets of Ubuntu (familiarity). This was validated by our experience of trying to get permission from a 5th case site, the village headman did not know the main researcher and rejected their request to conduct research in his village stating, "go and conduct your research in your village". Interesting to note is that, even though local councilors and village headman do not operate under the same law, they share an ethos. Our experience of getting permission from the Local constituency through official e-mail communication and telephonic conversations was met with apprehension. The documentation also contained the various ethical clearances from the university which would ordinarily suffice as evidence of legitimacy to engage, however, within this context, familiarity with the individual was highly ranked. The councilor indicated that their offices deal with many sensitive matters and therefore, even though he has received our documentation, he insisted that we visit his office-in-person to get the approval. We achieved this by sending a trusted community member from the constituency with whom we had familiarity and got the authorization granted. However, our co-design sessions did not yield that aspect, but rather indicated that the councilors may grant or reject researchers request for authorization and not provide an alternative route.
    Once a village headman has given permission to the researcher, he informs his secretary for noting and proceeds to inform various stakeholders depending on the nature of the research. These could be schools, churches, various community-based committees (water, public heath, community policing, etc.). However, he does inform his Kapatashu and often goes onto radio to make announcements to villages. He also informs any villagers he meets and neighbors too on an ad hoc-basis or while rendezvousing. Once the message reaches the villagers, they get a chance to agree or disagree with the dates proposed (tenet - Collective Unity). This is imperative as there are various interventions by different organisations that happen, and due to miscommunication between councilors and village headman, there might be engagements that go unaccounted for and villagers unavailable to attend community meetings. Once a date is agreed upon, the village headman communicates to the researcher for the research to go ahead. Not everyone hears the same information and as such the verbal face-to-face communication by neighbors also serves as a way of communicating community meetings. This form of communication is at sometimes referred to as social capital, the ability to trust what your neighbor tells you (tenets - neighbourliness, trust). It is also key especially within the communities that we are working since they have intermittent to no GSM connectivity. Community engagement is not a static activity, but rather iterative, as such, constant maintenance and involvement in community affairs is vital to keeping the engagement activity. The protocols may change as village members are constantly on the move and in search of various opportunities. In our case, many university students were home (in the villages) as most learning was happing online and economically, it was better to cut the costs of city living. Others move to nearby towns in search of employment and other business prospects. Therefore, the constant communication ensures that researchers are aware of shifts in demographics and community affairs. The above presented co-CEP in Figure 2, was validated through iteration, and it is the result of 4 co-design sessions merged. The components and relationships of co-CEP were mirrored across all 4 co-design sessions with CaseSite3 providing more context on the separation in operation between the councilor and headman in terms of jurisdiction and powers.
    Youths, comprised of university students, out of school youths, and some village elders made up the attendees of the community meetings. When reflecting on this composition of the attendees to the community meetings which is not common in African communities, the researcher interacted with the senior headman who indicated that
    "When it comes to topics related to technology, we are most likely only to get young people interested. Although we invited the village people to come for these meetings. I am also starting to notice that people hardly attend village meetings these days. I have no idea why, maybe they are not interested in the "iinima yeenghundwa" (things being discussed)" - CaseSite2OM1
    As presented in the methodology of this paper, communication was mainly held in Oshikwanyama. Therefore, we could not find a fitting word of 'Kapatashu' since they serve as both a section head and administrative assistant to the village headman. Therefore, we resort to referring to them as Kapatashu.
5. Discussion and Conclusion
    This paper presented a co-design community engagement protocol (co-CEP) that was co-designed in 4 villages within the Local constituency. The co-CEP is comprised of a set of key stakeholders that need to be consulted and those that need to be informed for successful engagement of socio-technical and more specifically cybersecurity research in rural African communities. The identified tenets from Ubuntu and Uushiindaism as theories under afro-centric epistemology provide a starting point for guidance in data collection instrument design, analysis, and presentation of results from research endeavors. We depart from this paper with the caution of from [33] that research in African contexts must centre Africans and not limit them to the periphery of researchers, this also includes research methods. Hence the novelty of using the above stated theories for guidance in research design.
    The study was limited in that the co-CEP was co-designed within one constituency in northern Namibia. This presents a homogenous population in terms of language, culture, ethos, and some administrative activities. As such future research should look at understanding engagement protocols in other rural underserved African communities. Those results would allow for an expansion of the presented co-CEP. Additionally, we also propose that our co-design CEP also be evaluated by researchers in other contexts in rural Africa and elsewhere. As such those results could also impact the design of national cybersecurity awareness campaigns and strategies elsewhere. Similarly, the messaging of socio-technical engagements by researchers can yield better reciprocity for rural community inhabitants beyond the dissemination of research outputs in academic publications [12]. Lastly, we propose that further research be conducted to understand the cybersecurity practices of rural communities and their technological appropriation, adoption, and assimilation now that a step towards trust building and inroads into rural communities has been co-designed.
References 
[1] International Telecommunication Union, "2021 Measuring digital development: Facts and figures," Geneva, 2021. [Online]. Available: https://www.itu.int/en/mediacentre/Documents/
MediaRelations/ITU Facts and Figures 2019 - Embargoed 5 
November 	1200 	CET.pdf%0Ahttps://www.itu.int/en/ITU-D/
Statistics/Pages/facts/default.aspx
[2] C. Rey-Moreno, R. Blignaut, W. D. Tucker, and J. May, "An in-depth study of the ICT ecosystem in a South African rural community: unveiling expenditure and communication patterns," Inf Technol Dev, vol. 22, no. sup1, pp. 101-120 (2016), doi: 10.1080/02681102.2016.1155145.
[3] M. Hasbi and A. Dubus, "Determinants of Mobile Broadband Use in Developing Economies: Evidence from Sub-Saharan Africa," 
Telecomm Policy, vol. 44, no. 5, pp. 1-34 (2020).
[4] C. Stork, E. Calandro, and A. Gillwald, "Internet going mobile : internet access and use in 11 African countries," Info-The journal of policy, regulation and strategy for telecommunications, vol. 15, no. 5, pp. 34-51 (2013), doi: 10.1108/info-05-2013-0026.
[5] Namibia Statistics Agency, "Namibia 2011 Population & Housing Census," 2014. [Online]. Available: http://www.nsa.org.na/files/ downloads/Namibia 2011 Population and Housing Census Main Report.pdf
[6] M. M. Ujakpa et al., "Understanding Mobile Phone Use in Electricity Scarce Context: Extended TAM for Sub-Saharan African Countries," in IST-Africa 2021 Conference Proceedings, pp. 1-8 (2021).
[7] K. Fröhlich, "Evaluating the Effects of e-Government Initiatives on Citizen-centric Goals at Selected Namibian Government Ministry," in IST-Africa 2017 Conference Proceedings, pp. 1-9 (2017).
[8] P. B. Maoneke, F. B. Shava, A. M. Gamundani, M. Bere-Chitauro, and I. Nhamu, "ICTs use and cyberspace risks faced by adolescents in Namibia," in Proceedings of the Second African Conference for Human Computer Interaction: Thriving Communities, pp. 109-117 (2018). doi: 10.1145/3283458.3283483.
[9] P. Markert, D. V. Bailey, M. Golla, M. Dürmuth, and A. J. Aviv, "On the Security of Smartphone Unlock PINs," ACM Transactions on Privacy and Security, vol. 24, no. 4, pp. 1-36 (2021), doi: 10.1145/3473040.
[10] G. T. Nhinda and F. Bhunu Shava, "Towards the use of Participatory Methods in Cybersecurity research in rural Africa: A grassroots Approach," in 2021 3rd International Multidisciplinary Information Technology and Engineering Conference, IMITEC 2021, Windhoek: IEEE, pp. 1-8 (2021). doi: 10.1109/IMITEC52926.2021.9714649.
[11] M. R. Lorini, A. Sabiescu, and N. Memarovic, "Collective Digital Storytelling in Community-based co-design projects. An Emergent Approach," The Journal of Community Informatics, vol. 13, no. 1 (2017), doi: 10.15353/joci.v13i1.3296.
[12] F. Ssozi-Mugarura, E. Blake, and U. Rivett, "Supporting community needs for rural water management through community-based co-design," in ACM International Conference Proceeding Series, pp. 91100 (2016). doi: 10.1145/2940299.2940311.
[13] G. Kapuire, H. Winschiers-Theophilus, and M. Brereton, "Deriving Engagement Protocols within Community- Based Co-Design Projects in Namibia," in 14th International Conference on So- cial Implications of Computers in Developing Countries (ICT4D), Yogyakarta, Indonesia, pp. 381-393 (2017).
[14] V. Venkatesh, T. A. Sykes, and X. Zhang, "ICT for development in rural India: A Longitudinal study of women's health outcomes," MIS Quarterly, vol. 44, no. 2, pp. 1-56 (2020).
[15] G. E. Iyawa et al., "Digital Transformation and Global Health in Africa," in Handbook of Global Health, Springer International Publishing, pp. 1-32 (2021). doi: 10.1007/978-3-030-05325-3_6-1.
[16] S. P. Shihomeka, "Engaging citizens: Youth, mobile phones, political leadership and inclusive democracy in the Ohangwena Region, Namibia," NAWA Journal of Language and Communication (NJLM), vol. 11, no. 1, pp. 4-17 (2017).
[17] F. Huntinghawk, C. Richard, S. Plosker, and G. Srivastava, "Expanding Cybersecurity Knowledge through an Indigenous Lens: A First Look," in In 2020 Canadian Conference on Electrical and Computer Engineering, pp. 1-4 (2020). doi: 10.1109/CCECE47787.2020.9255753.
[18] S. Plosker and G. Srivastava, "Cybersecurity Education in Rural Indigenous Canada," in In 2021 Canadian Conference on Electrical and Computer Engineering, IEEE, pp. 1-6 (2021). doi: 10.1109/ CCECE53047.2021.9569147.
[19] G. K. Kapuire et al., "Community-based co-design in Okomakuara: A contribution to 'Design in the wild,'" ACM International Conference Proceeding Series, vol. 2, pp. 207-208 (2014), doi: 10.1145/2662155.2662204.
[20] A. Singh and K. Chatterjee, "Security and privacy issues of electronic healthcare system: A survey," Journal of Information and Optimization Sciences, vol. 40, no. 8, pp. 1709-1729 (Nov. 2019), doi: 10.1080/02522667.2019.1703265.
[21] S. Khandelwal and A. Chaudhary, "COVID-19 pandemic &amp; cyber security issues: Sentiment analysis and topic modeling approach," Journal of Discrete Mathematical Sciences and Cryptography, vol. 25, no. 
4, pp. 987-997 (May 2022), doi: 10.1080/09720529.2022.2072421.
[22] D. Craigen, N. Diakun-Thibault, and R. Purse, "Defining Cybersecurity," Technology Innovation Management Review, vol. 4, no. 10, pp. 13-21 (2014), doi: 10.22215/timreview835.
[23] N. Gcaza and R. von Solms, "Cybersecurity Culture : An Ill-Defined Problem," in 10th IFIP World Conference on Information Security Education (WISE), pp. 98-109 (2017).
[24] M. Grobler, Z. Dlamini, S. Ngobeni, and A. Labuschagne, "Towards a cyber security aware rural community," in Proceedings of the 2011 Information Security for South Africa (ISSA) Conference., pp. 1-7 (2011). [Online]. Available: http://goo.gl/680YtV
[25] T. Winkler, "At the Coalface: Community-University Engagements and Planning Education," J Plan Educ Res, vol. 33, no. 2, pp. 215-227 (2013), doi: 10.1177/0739456X12474312.
[26] H. Winschiers-Theophilus, T. Zaman, and A. Yeo, "Reducing ' white elephant ' ICT4D projects : A Community- Researcher Engagement," in Proceedings of the 7th International Conference on Communities and Technologies, pp. 99-107 (2015).
[27] E. Nagyfejeo and B. von Solms, "Why Do National Cybersecurity Awareness Programmes Often Fail?," International Journal of 
Information Security and Cybercrime, vol. 9, no. 2, pp. 18-27 (2020), doi: 10.19107/ijisc.2020.02.03.
[28] M. Laura Ramírez Galleguillos and A. Cokun, "How do i matter? a review of the participatory design practice with less privileged participants," ACM International Conference Proceeding Series, vol. 1, pp. 137-147 (2020), doi: 10.1145/3385010.3385018.
[29] R. Smith, "A co-creation design framework to support elderly rural women in refining an ICT platform by," Philosophiae Doctor: Informatics, University of Pretoria (2019).
[30] H. Winschiers-theophilus, S. Chivuno-kuria, G. K. Kapuire, N. J. Bidwell, and E. Blake, "Being Participated - A Community Approach," in Proceedings of the 11th Biennial Participatory Design Conference, New York: ACM, pp. 1-10 (2010).
[31] N. J. Bidwell, "Anchoring Design in Rural Customs of Doing and Saying," in IFIP Conference on Human-Computer Interaction, pp. 686699 (2009).
[32] T. Iyamu, "The Role of African Proverbs in Advancing Information Systems Research," The African Journal of Information Systems, vol. 13, 
no. 4, pp. 476-492 (2021), [Online]. Available: https://digitalcommons. kennesaw.edu/ajis/vol13/iss4/3/.
[33] Q. Mkabela, "Using the Afrocentric Method in Researching 
Indigenous African Culture," The qualitative Report, vol. 10, no. 1, pp. 178-189 (2005), [Online]. Available: https://nsuworks.nova.edu/ tqr/vol10/iss1/10/.
[34] P. A. Mbenzi and S. N. Ashikuti, "Uushiindaism as a collective poverty alleviation mechanism and social support," Journal of University of Namibia Language Centre, vol. 3, no. 1, pp. 2026-8297 (2018).
[35] P. A. Mbenzi, "The Contribution of Finnish Missionaries Towards the Development of Oshiwambo Language and Culture," in INTERTWINED HISTORIES, M. Kaartinen, L. Koivunen, and N. Shiweda, Eds., University of Turku, pp. 111-117 (2019).
[36] Namibia Statistics Agency, "2011 Population and Housing Census - Ohangwena Regional Profile," (2014).
476 	G. T. NHINDA AND F. B. SHAVA

A CO-DESIGNED COMMUNITY ENGAGEMENT PROTOCOL AS A CATALYST 	477




        </p>
</body>
</html>